name: "Cache"

on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        target: [ociImage-amd64, ociImage-arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - uses: cachix/cachix-action@v14
      with:
        name: tuckershea
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#${{ matrix.target }}
